Build error Fixup

diff --git a/.github/workflows/SGSI_Build.yml b/.github/workflows/SGSI_Build.yml
--- a/.github/workflows/SGSI_Build.yml
+++ b/.github/workflows/SGSI_Build.yml
@@ -1,85 +1,80 @@
-# This is a basic workflow to help you get started with Actions
-
 name: SGSI_Build
 
 on:
   watch:
     types: [started]
-    
-env:              
-  ROM_URL: 'https://dl.google.com/developers/android/sc/images/ota/redfin-ota-spp2.210219.008-3d61e529.zip'
-  ZIP_NAME: 'update.zip'
-  OS_TYPE: 'Generic'
-  BUILD_TYPE: 'ab'
-  REPACK_NAME: 'SGSI.zip'
-  VERSION: '12'
-  upload_action-gh-release: 'true'
-  SETUP: 'true'
-  
+
 jobs:
   build:
     runs-on: ubuntu-20.04
 
     steps:
-       - name: Checkout
-         uses: actions/checkout@main
-       
-       - name: Clean Up
-         uses: rokibhasansagar/slimhub_actions@main
-           
-       - name: Setting up the SPICES
-         run: |
-            sudo apt-get install -y git wget git zip unzip curl axel
+      - name: Checkout
+        uses: actions/checkout@v2
 
-       - name: Cloning SGSI source code
-         run: |
-             git clone --recurse-submodules https://github.com/xiaoxindada/SGSI-build-tool.git -b 12 $GITHUB_WORKSPACE/SGSI-build-tool
-           
-       - name: Download zip...
-         run: |
-            cd $GITHUB_WORKSPACE/SGSI-build-tool
-            mkdir ./tmp
-            wget -U "Mozilla/5.0" $ROM_URL -O "$GITHUB_WORKSPACE/SGSI-build-tool/tmp/$ZIP_NAME"
-            echo "zip_file: $(ls "$GITHUB_WORKSPACE/SGSI-build-tool/tmp/")"
+      - name: Load Configuration
+        uses: falti/dotenv-action@v0.2.5
+        id: config
+        with:
+          path: config.env
+
+      - name: Check Configuration
+        run: |
+          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
+          required "${{ steps.config.outputs.rom_url }}" "ROM_URL config"
+          required "${{ steps.config.outputs.build_type }}" "BUILD_TYPE config"
+          required "${{ steps.config.outputs.os_type }}" "OS_TYPE config"
+          required "${{ steps.config.outputs.zip_name }}" "ZIP_NAME config"
+          required "${{ steps.config.outputs.version }}" "VERSION config"
+          required "${{ steps.config.outputs.repack_name }}" "REPACK_NAME config"
+
+      - name: Cleanup workspace
+        run: |
+           docker rmi `docker images -q`
+           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
+           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox* google* dotnet* powershell openjdk* php*
+           sudo -E apt-get update
+           sudo -E apt-get -y autoremove --purge
+           sudo -E apt-get clean
+           df -h
+         
+      - name: Initializing Environment
+        run: |
+          sudo apt-get install -y git wget git zip unzip curl axel
+
+      - name: Cloning SGSI source code
+        run: |
+          git clone --recurse-submodules https://github.com/xiaoxindada/SGSI-build-tool.git -b 12 $GITHUB_WORKSPACE/SGSI-build-tool
             
-       - name: Setup Tool Utils...
-         if: env.SETUP == 'true'
-         run: |
-            sudo sed -i 's/USE_MIRROR_FOR_PIP\=true/USE_MIRROR_FOR_PIP\=false/' $GITHUB_WORKSPACE/SGSI-build-tool/setup.sh
-            sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/setup.sh
-            # sudo apt-get -y --purge remove "adoptopenjdk-11-hotspot"
-            java -version
+      - name: Setup sGSI tools requirements
+        run: |
+          sudo sed -i 's/USE_MIRROR_FOR_PIP\=true/USE_MIRROR_FOR_PIP\=false/' $GITHUB_WORKSPACE/SGSI-build-tool/setup.sh
+          sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/setup.sh
+         # sudo apt-get -y --purge remove "adoptopenjdk-11-hotspot"
+         # java -version
             
-       - name: Building AB DEVICES SGSI...
-         if: env.BUILD_TYPE == 'AB' || env.BUILD_TYPE == 'ab'
-         run: |
-            sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/make.sh --AB $OS_TYPE $ZIP_NAME --fix-bug
+      - name: Build SGSI
+        run: |
+          sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/url2SGSI.sh "${{ steps.config.outputs.rom_url }}" "${{ steps.config.outputs.os_type }}" "${{ steps.config.outputs.build_type }}"
 
-       - name: Building A-only DEVICES SGSI...
-         if: env.BUILD_TYPE == 'a-only'
-         run: |
-            sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/make.sh --a-only $OS_TYPE $ZIP_NAME --fix-bug     
+      - name: Repack Output File
+        run: |            
+         cd $GITHUB_WORKSPACE/SGSI-build-tool
+         mkdir -p upload
+         zip -r ${{ steps.config.outputs.repack_name }} ./SGSI/*
+         if [[ $(du -sb "${{ steps.config.outputs.repack_name }}" | awk '{print $1}') -gt 2097152000 ]];then
+             echo -e "split packaging..."
+             tar -cpzf - "${{ steps.config.outputs.repack_name }}" | split -d -b 1024m - "upload/${{ steps.config.outputs.repack_name }}"
+         else
+             mv "${{ steps.config.outputs.repack_name }}" "upload/${{ steps.config.outputs.repack_name }}"
+         fi
+         ls "upload"
 
-       - name: Repack output file ...
-         run: |            
-             cd $GITHUB_WORKSPACE/SGSI-build-tool
-             pwd
-             mkdir -p upload
-             zip -r $REPACK_NAME ./SGSI/*
-             if [[ $(du -sb "$REPACK_NAME" | awk '{print $1}') -gt 2097152000 ]];then
-                 echo -e "split packaging..."
-                 tar -cpzf - "$REPACK_NAME" | split -d -b 1024m - "upload/$REPACK_NAME"
-             else
-                 mv $REPACK_NAME upload/$REPACK_NAME
-             fi
-             ls "upload"
-
-       - name: Upload SGSI to action-gh-release...
-         if: env.upload_action-gh-release == 'true'
-         uses: ncipollo/release-action@v1.8.6
-         with:
-           artifacts: ${{ github.workspace }}/SGSI-build-tool/upload/*
-           name: xiaoxinSGSI-${{ env.OS_TYPE }}-${{ env.BUILD_TYPE }}-Android${{ env.VERSION }}-unpack
-           tag: xiaoxinSGSI-${{ env.OS_TYPE }}-${{ env.BUILD_TYPE }}-Android${{ env.VERSION }}-${{ github.run_number }}
-           bodyFile: "${{ github.workspace }}/SGSI-build-tool/SGSI/build_info.txt"
-           token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Upload SGSI to GH-Release
+        uses: ncipollo/release-action@v1.8.6
+        with:
+          artifacts: ${{ github.workspace }}/SGSI-build-tool/upload/*
+          name: "${{ steps.config.outputs.os_type }}${{ steps.config.outputs.build_type }}-Android${{ steps.config.outputs.version }}-unpack"
+          tag: "${{ steps.config.outputs.os_type }}${{ steps.config.outputs.build_type }}-${{ steps.config.outputs.version }}-${{ github.run_number }}"
+          bodyFile: "${{ github.workspace}}/SGSI-build-tool/SGSI/build_info.txt"
+          token: ${{ secrets.GITHUB_TOKEN }}
